# Generated by Django 4.2.9 on 2024-01-10 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPlatformOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_type', models.CharField(choices=[('E-commerce', 'E-commerce'), ('Content Creator and Influencers', 'Content Creator and Influencers'), ('Health and Fitness', 'Health and Fitness'), ('Technology and Software Companies', 'Technology and Software Companies'), ('Hospitality and Tourism', 'Hospitality and Tourism')], max_length=255)),
                ('social_service', models.CharField(choices=[('YouTube', 'YouTube'), ('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('LinkedIn', 'LinkedIn')], max_length=255)),
                ('like_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('subscriber_count', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
