# Generated by Django 4.2.9 on 2024-01-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_linkedinpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedinpost',
            name='attachment',
        ),
        migrations.AddField(
            model_name='linkedinpost',
            name='attachment_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
