# Generated by Django 4.2.9 on 2024-01-16 19:32

from django.db import migrations, models
from datetime import datetime, time


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_linkedinpost_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinpost',
            name='publish_date',
            field=models.DateField(default=datetime(2024, 1, 16)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linkedinpost',
            name='publish_time',
            field=models.TimeField(default=time(23, 59)),
            preserve_default=False,
        ),
    ]
