# Generated by Django 4.2.9 on 2024-01-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_linkedinpost_publish_date_linkedinpost_publish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedinpost',
            name='publish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='linkedinpost',
            name='publish_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
