# Generated by Django 4.2.9 on 2024-01-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_facebookpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookpost',
            name='title',
        ),
        migrations.RemoveField(
            model_name='facebookpost',
            name='video_title',
        ),
        migrations.AddField(
            model_name='facebookpost',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
