# Generated by Django 4.2.9 on 2024-01-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_facebookpost_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpost',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
