# Generated by Django 4.2.9 on 2024-01-10 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialservice',
            name='user',
        ),
        migrations.DeleteModel(
            name='AudienceType',
        ),
        migrations.DeleteModel(
            name='SocialService',
        ),
    ]
